<?= $this->doctype() ?>
<html lang="en" ng-app>
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Travel outlet Backend')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

		<script src="https://ajax.googleapis.com/ajax/libs/webfont/1.6.16/webfont.js"></script>
		<script>
          WebFont.load({
            google: {"families":["Poppins:300,400,500,600,700","Roboto:300,400,500,600,700"]},
            active: function() {
                sessionStorage.fonts = true;
            }
          });
		</script>
        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/backend-theme/img/favicon.ico'])
            ->prependStylesheet($this->basePath('backend-theme/assets/vendors/base/vendors.bundle.css'))
            ->prependStylesheet($this->basePath('backend-theme/assets/demo/demo5/base/style.bundle.css'))
            ->appendStylesheet($this->basePath('backend-theme/login.css'))
        ?>

        <!-- Scripts -->
        <?= $this->headScript()
        ->appendFile($this->basePath('backend-theme/assets/vendors/base/vendors.bundle.js'))
        ->appendFile($this->basePath('backend-theme/assets/demo/demo5/base/scripts.bundle.js'))
        ?>
    </head>
    <body class="m--skin- m-header--fixed m-header--fixed-mobile m-aside-left--enabled m-aside-left--skin-dark m-aside-left--offcanvas m-footer--push m-aside--offcanvas-default">
    	<div class="m-grid m-grid--hor m-grid--root m-page">
			<div class="m-grid__item m-grid__item--fluid m-grid m-grid--hor m-login m-login--singin m-login--2 m-login-2--skin-2" id="m_login">
            	<div class="m-grid__item m-grid__item--fluid m-login__wrapper">
            		<div class="m-login__container">
            			<div class="m-login__logo">
            				<a href="<?= $this->url('backend')?>">
            				<img src="/backend-theme/img/logo.png">
            				</a>
            			</div>
            			<?= $this->content ?>
            		</div>
            	</div>
            </div>

    </div>
<?php $this->inlineScript()->captureStart();
echo <<<JS
JS;
$this->inlineScript()->captureEnd();
?>
        <?= $this->inlineScript() ?>
    </body>
</html>