<?php $container = $this->container;?>
<ul class="<?= $this->navigation()->menu()->getUlClass(); ?>">
    <?php foreach ($container as $page): ?>
    	<?php if($page->__isset('params')){
    	    $params = $page->getParams();
    	    $params['lang'] = $this->layout()->lang;
    	    $page->setParams($params);
    	}?>
        <?php if (!$this->navigation()->accept($page)) continue; ?>
        <li class="nav-item<?php if ($page->isActive(true)) echo ' active' ?>">
        	<a class="nav-link" href="<?= $page->getHref() ?>"<?php if ($page->getTarget() != ""): ?> target="<?= $page->getTarget(); ?>"<?php endif; ?>>
            	<?= $this->translate($page->getLabel()) ?>
        	</a>
    	</li>
        <?php
    endforeach ?>
</ul>