<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional //EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:v="urn:schemas-microsoft-com:vml" style="background: #f3f3f3; min-height: 100%;">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body style="-ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; background-color: #EBEFF8; box-sizing: border-box; color: #333; font-family: 'Roboto', Arial, Helvetica, sans-serif; font-size: 15px; font-weight: normal; line-height: 1.3; margin: 0; min-width: 100%; padding: 0; text-align: left; width: 100% !important;">
<table width="100%" border="0" cellpadding="0" cellspacing="0" class="body" style="background: #EBEFF8; border-collapse: collapse; border-spacing: 0; color: #0a0a0a; font-family: 'Roboto', Arial, Helvetica, sans-serif; font-weight: normal; height: 100%; line-height: 1.3; margin: 0; padding: 0; text-align: left; vertical-align: top; width: 100%;">
    <tr style="padding: 0; text-align: left; vertical-align: top;">
        <td class="wrapper-inner" align="center" valign="top" style="-moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; color: #0a0a0a; font-family: 'Roboto', Arial, Helvetica, sans-serif; font-weight: normal; hyphens: auto; line-height: 1.3; margin: 0; max-width: 808px !important; min-width: 808px !important; padding: 110px 20px !important; text-align: left; vertical-align: top; width: 808px !important; word-wrap: break-word;">
            <table width="768" align="center" border="0" cellpadding="0" cellspacing="0" class="container content-wrapper main-content" style="background: #fefefe; background-color: #ffffff; border: 1px solid #DDDDDD; border-collapse: collapse; border-radius: 0; border-spacing: 0; margin: 0 auto; margin-bottom: 20px; max-width: 768px !important; min-width: 768px !important; padding: 0; text-align: inherit; vertical-align: top; width: 768px !important;">
                <tr style="padding: 0; text-align: left; vertical-align: top;">
                    <td class="full-width" style="-moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; color: #0a0a0a; font-family: 'Roboto', Arial, Helvetica, sans-serif; font-weight: normal; hyphens: auto; line-height: 1.3; margin: 0; padding: 0; text-align: left; vertical-align: top; width: 100% !important; word-wrap: break-word;">
                        <table class="full-width" style="border-collapse: collapse; border-spacing: 0; padding: 0; text-align: left; vertical-align: top; width: 100% !important;">
                            <tr style="padding: 0; text-align: left; vertical-align: top;">
                                <td class="header" style="-moz-hyphens: auto; -webkit-hyphens: auto; border-bottom: 1px solid #F5F7FC; border-collapse: collapse !important; color: #0a0a0a; font-family: 'Roboto', Arial, Helvetica, sans-serif; font-weight: normal; hyphens: auto; line-height: 1.3; margin: 0; padding: 0; text-align: left; vertical-align: top; word-wrap: break-word;">
                                    <table class="row" style="border-collapse: collapse; border-spacing: 0; display: table; padding: 0; position: relative; text-align: left; vertical-align: top; width: 100%;">
                                        <tr style="padding: 0; text-align: left; vertical-align: top;">
                                            <th class="small-6 large-6 columns header-logo" valign="middle" align="center" style="color: #0a0a0a; font-family: 'Roboto', Arial, Helvetica, sans-serif; font-weight: normal; height: 120px; line-height: 1.3; margin: 0 auto; min-height: 120px; padding: 0 40px !important; padding-bottom: 16px; padding-left: 24px; padding-right: 8px; text-align: left; vertical-align: middle !important; width: 50%;">
                                                <img src="<?= $this->serverUrl()?>/images/emails/logo.png" alt="Tojour" width="179" height="30" class="logo float-center" align="center" style="-ms-interpolation-mode: bicubic; clear: both; display: block; float: none; height: 30px; margin: 0 auto; max-width: 100%; outline: none; text-align: center; text-decoration: none; width: 179px;">
                                            </th>
                                            <th class="small-6 large-6 columns header-agent" valign="middle" style="background-color: #F5F7FC; color: #0a0a0a; font-family: 'Roboto', Arial, Helvetica, sans-serif; font-weight: normal; height: 120px; line-height: 1.3; margin: 0 auto; min-height: 120px; padding: 0 40px !important; padding-bottom: 16px; padding-left: 24px; padding-right: 8px; text-align: left; vertical-align: middle !important; width: 50%;">
                                                <div class="agent-name" style="color: #333333; font-size: 14px; height: 16px; line-height: 1.3em; padding-top: 8px;"><?= $this->agentName?></div>
                                                <div class="agent-phone" style="color: #3C63BC; font-size: 24px; font-weight: bold; line-height: 1.2em; text-decoration: none;"><?= $this->phone?></div>
                                            </th>
                                            <th class="expander" style="color: #0a0a0a; font-family: 'Roboto', Arial, Helvetica, sans-serif; font-weight: normal; line-height: 1.3; margin: 0; padding: 0; text-align: left;"></th>
                                        </tr>
                                    </table>
                                </td>
                            </tr>
                            <tr style="padding: 0; text-align: left; vertical-align: top;">
                                <th class="small-12 large-12 first last columns cover" valign="middle" style="border-bottom: 1px solid #F5F7FC; color: #0a0a0a; font-family: 'Roboto', Arial, Helvetica, sans-serif; font-weight: normal; line-height: 1.3; margin: 0 auto; padding: 33px 28px !important; padding-bottom: 16px; padding-left: 24px; padding-right: 24px; text-align: left; width: 100%;">
                                    <h2 class="cover-title" style="color: #0a0a0a; font-family: 'Roboto', Arial, Helvetica, sans-serif; font-size: 24px; font-weight: normal; line-height: 1.3; margin: 0; margin-bottom: 16px; padding: 0; text-align: left;">Dear Customer,</h2>
                                    <div class="cover-text" style="color: #333333; font-size: 16px !important; line-height: 1.4em !important;">My Name is <?= $this->agentName?>, I’m your persoanl travel expert.
                                        Below you will find information on the itinerary from <?= $this->origin?> to <?= $this->destination?> designed
                                        for your needs. To Ensure delivery of future email correspondence, please add
                                        <a href="mailto:<?= $this->agentEmail?>" style="color: #3C63BC; font-family: 'Roboto', Arial, Helvetica, sans-serif; font-weight: normal; line-height: 1.3; margin: 0; padding: 0; text-align: left; text-decoration: none;"><?= $this->agentEmail?></a> yo your adress book.
                                    </div>
                                </th>
                            </tr>

                            <!--Offers-->
							<?php foreach ($this->offers as $offer):?>
                            <tr style="padding: 0; text-align: left; vertical-align: top;">
                                <th class="offer" style="border-bottom: 1px solid #F5F7FC; color: #0a0a0a; font-family: 'Roboto', Arial, Helvetica, sans-serif; font-weight: normal; line-height: 1.3; margin: 0; padding: 30px 0 14px; text-align: left;">
                                    <table class="row" style="border-collapse: collapse; border-spacing: 0; display: table; padding: 0; position: relative; text-align: left; vertical-align: top; width: 100%;">
                                        <tr class="itinerary-top-row" style="padding: 0; text-align: left; vertical-align: top;">
                                            <th class="small-1 large-1 first columns offer-number" rowspan="2" style="color: #333; font-family: 'Roboto', Arial, Helvetica, sans-serif; font-weight: normal; line-height: 1.3; margin: 0 auto; padding: 0; padding-bottom: 3px; padding-left: 24px; padding-right: 8px; text-align: left; width: 32.33333px;">1</th>
                                            <th class="small-9 large-9 columns itinerary-title" colspan="3" style="color: #3C63BC; font-family: 'Roboto', Arial, Helvetica, sans-serif; font-size: 16px; font-weight: bold; line-height: 1.3; margin: 0 auto; padding: 0; padding-bottom: 3px; padding-left: 8px; padding-right: 8px; text-align: left; width: 419px;">
                                            <?= $this->title?> <b style="color: #333333; font-size: 16px; font-weight: bold;">(<?= $offer['carrier']?>)</b></th>
                                            <th class="small-2 large-2 last columns text-center" valign="middle" align="center" style="color: #0a0a0a; font-family: 'Roboto', Arial, Helvetica, sans-serif; font-weight: normal; line-height: 1.3; margin: 0 auto; padding: 0; padding-bottom: 3px; padding-left: 8px; padding-right: 24px; text-align: center; width: 128px;">
                                                <div class="itinerary-price" style="color: #333333; font-size: 20px; font-weight: bold;">$ <?= number_format($offer['total'], 2)?></div>
                                                <div class="itinerary-total" style="color: #666666; font-size: 12px;">Total</div>
                                            </th>
                                            <th class="expander" style="color: #0a0a0a; font-family: 'Roboto', Arial, Helvetica, sans-serif; font-weight: normal; line-height: 1.3; margin: 0; padding: 0; text-align: left;"></th>
                                        </tr>
                                        <tr style="padding: 0; text-align: left; vertical-align: top;">
                                            <th class="small-9 large-9 columns itinerary-title" colspan="3" style="color: #0a0a0a; font-family: 'Roboto', Arial, Helvetica, sans-serif; font-weight: normal; line-height: 1.3; margin: 0 auto; padding: 0; padding-bottom: 16px; padding-left: 8px; padding-right: 8px; text-align: left; width: 177.33333px;">
                                                <?php foreach ($offer['segments'] as $segment):?>
                                                <div>
                                                	<span style="color: #333333; font-size: 16px;"><?= $segment['origin'].' - '.$segment['destination']?>: <?= $segment['departureDate']->format('d M')?></span>
                                                	<span style="color: #333333; font-size: 16px; font-weight: bold;"><?= $segment['departureDate']->format('h:i A').' - '.$segment['arrivalDate']->format('h:i A')?></span>
                                                </div>
                                                <?php endforeach;?>
                                            </th>
                                            <th class="small-2 large-2 last columns itinerary-btn-col" valign="middle" align="center" style="color: #0a0a0a; font-family: 'Roboto', Arial, Helvetica, sans-serif; font-weight: normal; line-height: 1.3; margin: 0 auto; padding: 0; padding-bottom: 16px; padding-left: 8px; padding-right: 24px; text-align: left; width: 128px;">
                                                <table class="button radius details-btn" style="border-collapse: collapse; border-spacing: 0; margin: 0 0 16px 0; margin-bottom: 0; padding: 0; text-align: left; vertical-align: top; width: auto;">
                                                    <tr style="padding: 0; text-align: left; vertical-align: top;">
                                                        <td style="-moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; color: #0a0a0a; font-family: 'Roboto', Arial, Helvetica, sans-serif; font-weight: normal; hyphens: auto; line-height: 1.3; margin: 0; padding: 0; text-align: left; vertical-align: top; word-wrap: break-word;">
                                                            <table style="border-collapse: collapse; border-spacing: 0; padding: 0; text-align: left; vertical-align: top; width: 100%;">
                                                                <tr style="padding: 0; text-align: left; vertical-align: top;">
                                                                    <td style="-moz-hyphens: auto; -webkit-hyphens: auto; background: #3C63BC; border: none; border-collapse: collapse !important; border-radius: 5px; color: #fefefe; font-family: 'Roboto', Arial, Helvetica, sans-serif; font-weight: normal; hyphens: auto; line-height: 1.3; margin: 0; padding: 0; text-align: left; vertical-align: top; word-wrap: break-word;">
                                                                    <a href="<?= $this->checkoutUrl.sprintf("%'.09d\n", $offer['id'])?>" style="border: 0 solid #3C63BC; color: #fefefe; display: inline-block; font-family: Helvetica, Arial, sans-serif; font-size: 14px; font-weight: normal; line-height: 1.3; margin: 0; padding: 13px 30px; text-align: left; text-decoration: none; text-transform: uppercase; white-space: nowrap;">View details</a></td>
                                                                </tr>
                                                            </table>
                                                        </td>
                                                    </tr>
                                                </table>
                                            </th>
                                            <th class="expander" style="color: #0a0a0a; font-family: 'Roboto', Arial, Helvetica, sans-serif; font-weight: normal; line-height: 1.3; margin: 0; padding: 0; text-align: left;"></th>
                                        </tr>
                                    </table>
                                </th>
                            </tr>
                            <?php endforeach;?>

                            <!--Additional Notes-->

                            <tr style="padding: 0; text-align: left; vertical-align: top;">
                                <th class="additional" style="color: #0a0a0a; font-family: 'Roboto', Arial, Helvetica, sans-serif; font-weight: normal; line-height: 1.3; margin: 0; padding: 24px 0; text-align: left;">
                                    <table class="row" style="border-collapse: collapse; border-spacing: 0; display: table; padding: 0; position: relative; text-align: left; vertical-align: top; width: 100%;">
                                        <tr style="padding: 0; text-align: left; vertical-align: top;">
                                            <th class="small-6 large-6 first columns additional-left" valign="top" style="border-right: 1px solid #F5F7FC; color: #0a0a0a; font-family: 'Roboto', Arial, Helvetica, sans-serif; font-weight: normal; line-height: 1.3; margin: 0 auto; padding: 0; padding-bottom: 16px; padding-left: 24px; padding-right: 8px; text-align: left; width: 50%;">
                                                <table class="full-width" style="border-collapse: collapse; border-spacing: 0; padding: 0; text-align: left; vertical-align: top; width: 100% !important;">
                                                    <tr style="padding: 0; text-align: left; vertical-align: top;">
                                                        <td style="-moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; color: #0a0a0a; font-family: 'Roboto', Arial, Helvetica, sans-serif; font-weight: normal; hyphens: auto; line-height: 1.3; margin: 0; padding: 0; text-align: left; vertical-align: top; word-wrap: break-word;">
                                                            <img src="<?= $this->serverUrl()?>/images/emails/icn-time.png" width="70" height="70" class="additional-icn float-left" style="-ms-interpolation-mode: bicubic; clear: both; display: block; float: left; height: 70px; margin-right: 20px; max-width: 100%; outline: none; text-align: left; text-decoration: none; width: 70px;">
                                                            <div class="additional-fares" style="font-size: 12px; font-weight: bold; line-height: 1.3em; margin-bottom: 6px;">
                                                                Fares are not guaranteed until tickets are issued.
                                                            </div>
                                                            <div class="additional-fares-note" style="color: #666666; font-size: 12px; line-height: 1.3em;">
                                                                I encourage you to call me with any questions you have.
                                                            </div>
                                                        </td>
                                                    </tr>
                                                </table>
                                            </th>
                                            <th class="small-6 large-6 first columns additional-right" valign="top" style="color: #0a0a0a; font-family: 'Roboto', Arial, Helvetica, sans-serif; font-weight: normal; line-height: 1.3; margin: 0 auto; padding: 0; padding-bottom: 16px; padding-left: 24px; padding-right: 8px; text-align: left; width: 50%;">
                                                <table class="full-width" style="border-collapse: collapse; border-spacing: 0; padding: 0; text-align: left; vertical-align: top; width: 100% !important;">
                                                    <tr style="padding: 0; text-align: left; vertical-align: top;">
                                                    	<td>
                                                            <img src="<?= $this->serverUrl()?>/images/emails/icn-support.png" width="70" height="70" class="additional-icn float-left" style="-ms-interpolation-mode: bicubic; clear: both; display: block; float: left; height: 70px; margin-right: 20px; max-width: 100%; outline: none; text-align: left; text-decoration: none; width: 70px;">
                                                            <div class="additional-book" style="font-size: 12px;">To book or for additional options
                                                                call:
                                                            </div>
                                                            <div class="additional-phone"><a href="tel:<?= $this->phone?>" style="color: #EB5757; display: inline-block; font-family: 'Roboto', Arial, Helvetica, sans-serif; font-size: 18px; font-weight: bold; line-height: 1.3; margin: 0; margin-bottom: 10px; padding: 0; text-align: left; text-decoration: none;"><?= $this->phone?></a></div>
                                                            <div class="additional-contact" style="color: #666666; font-size: 12px;">or contact me 24/7 by e-mail
                                                            </div>
                                                            <div class="additional-email">
                                                                <a href="mailto:<?= $this->agentEmail?>" class="email-link" style="color: #3C63BC; font-family: 'Roboto', Arial, Helvetica, sans-serif; font-size: 12px; font-weight: normal; line-height: 1.3; margin: 0; padding: 0; text-align: left; text-decoration: underline;"><?= $this->agentEmail?></a>
                                                            </div>
                                                        </td>
                                                    </tr>
                                                </table>
                                            </th>
                                        </tr>
                                    </table>
                                </th>
                            </tr>

                        </table>
                    </td>
                </tr>
            </table>
            <table width="768" align="center" border="0" cellpadding="0" cellspacing="0" class="container content-wrapper footer" style="background: #fefefe; background-color: #ffffff; border: 1px solid #DDDDDD; border-collapse: collapse; border-radius: 0; border-spacing: 0; margin: 0 auto; max-width: 768px !important; min-width: 768px !important; padding: 0; text-align: inherit; vertical-align: top; width: 768px !important;">
                <tr style="padding: 0; text-align: left; vertical-align: top;">
                    <td class="full-width" style="-moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; color: #0a0a0a; font-family: 'Roboto', Arial, Helvetica, sans-serif; font-weight: normal; hyphens: auto; line-height: 1.3; margin: 0; padding: 0 20px; text-align: left; vertical-align: top; width: 100% !important; word-wrap: break-word;">
                        <table class="full-width" style="border-collapse: collapse; border-spacing: 0; padding: 0; text-align: left; vertical-align: top; width: 100% !important;">
                            <tr style="padding: 0; text-align: left; vertical-align: top;">
                                <th class="footer-top" style="border-bottom: 1px solid #F5F7FC; color: #0a0a0a; font-family: 'Roboto', Arial, Helvetica, sans-serif; font-size: 16px; font-weight: normal; line-height: 1.3; margin: 0; padding: 30px 0; text-align: left;">
                                    <table class="row" style="border-collapse: collapse; border-spacing: 0; display: table; padding: 0; position: relative; text-align: left; vertical-align: top; width: 100%;">
                                        <tr style="padding: 0; text-align: left; vertical-align: top;">
                                            <th class="small-12 large-12 columns first last" style="color: #0a0a0a; font-family: 'Roboto', Arial, Helvetica, sans-serif; font-weight: normal; line-height: 1.3; margin: 0 auto; padding: 0; padding-bottom: 16px; padding-left: 24px; padding-right: 24px; text-align: left; width: 100%;">Sincerely,<br><?= $this->agentName?></th>
                                        </tr>
                                        <tr style="padding: 0; text-align: left; vertical-align: top;">
                                            <th class="small-12 large-12 columns first last" style="color: #0a0a0a; font-family: 'Roboto', Arial, Helvetica, sans-serif; font-weight: normal; line-height: 1.3; margin: 0 auto; padding: 0; padding-bottom: 16px; padding-left: 24px; padding-right: 24px; text-align: left; width: 100%;">
                                                E-Mail: <a href="mailto:<?= $this->agentEmail?>" class="footer-email" style="color: #3C63BC; font-family: 'Roboto', Arial, Helvetica, sans-serif; font-weight: normal; line-height: 1.3; margin: 0; padding: 0; text-align: left; text-decoration: none;"><?= $this->agentEmail?></a><br>
                                                Direct Line: <?= $this->phone?>
                                            </th>
                                        </tr>
                                    </table>
                                </th>
                            </tr>
                            <tr style="padding: 0; text-align: left; vertical-align: top;">
                                <th class="footer-bottom" style="color: #0a0a0a; font-family: 'Roboto', Arial, Helvetica, sans-serif; font-size: 12px; font-weight: normal; line-height: 1.3; margin: 0; padding: 32px 0 45px; text-align: center;">
                                    <table class="row" style="border-collapse: collapse; border-spacing: 0; display: table; padding: 0; position: relative; text-align: left; vertical-align: top; width: 100%;">
                                        <tr style="padding: 0; text-align: left; vertical-align: top;">
                                            <th class="small-12 large-12 columns first last" align="center" style="color: #0a0a0a; font-family: 'Roboto', Arial, Helvetica, sans-serif; font-weight: normal; line-height: 1.3; margin: 0 auto; padding: 0; padding-bottom: 16px; padding-left: 24px; padding-right: 24px; text-align: left; width: 100%;">
                                                <img src="<?= $this->serverUrl()?>/images/emails/logo-footer.png" alt="Logo" width="139" height="24" class="footer-logo float-center" style="-ms-interpolation-mode: bicubic; clear: both; display: block; float: none; margin: 0 auto; margin-bottom: 15px; max-width: 100%; outline: none; text-align: center; text-decoration: none; width: auto;">
                                            </th>
                                            <th class="expander" style="color: #0a0a0a; font-family: 'Roboto', Arial, Helvetica, sans-serif; font-weight: normal; line-height: 1.3; margin: 0; padding: 0; text-align: left;"></th>
                                        </tr>
                                        <tr style="padding: 0; text-align: left; vertical-align: top;">
                                            <th class="small-12 large-12 columns first last footer-text text-center" align="center" style="color: #333333; font-family: 'Roboto', Arial, Helvetica, sans-serif; font-weight: normal; line-height: 1.4em; margin: 0 auto; padding: 0; padding-bottom: 16px; padding-left: 24px; padding-right: 24px; text-align: center; width: 100%;">
                                                Wowfare is a part of The
                                                Travel Outlet of Virginia, LLC, major international consolidator for
                                                travel and related services.
                                                <div class="footer-copyright" style="color: #7d7d7d;">
                                                    © <?= date('Y')?> The Travel Outlet of Virginia, LLC. All rights reserved.
                                                </div>
                                            </th>
                                            <th class="expander" style="color: #0a0a0a; font-family: 'Roboto', Arial, Helvetica, sans-serif; font-weight: normal; line-height: 1.3; margin: 0; padding: 0; text-align: left;"></th>
                                        </tr>
                                        <tr style="padding: 0; text-align: left; vertical-align: top;">
                                            <th class="small-12 large-12 columns first last" align="center" style="color: #0a0a0a; font-family: 'Roboto', Arial, Helvetica, sans-serif; font-weight: normal; line-height: 1.3; margin: 0 auto; padding: 0; padding-bottom: 16px; padding-left: 24px; padding-right: 24px; text-align: left; width: 100%;">
                                                <img src="<?= $this->serverUrl()?>/images/emails/partners.png" alt="Partners" width="281" height="40" class="footer-partners float-center" style="-ms-interpolation-mode: bicubic; clear: both; display: block; float: none; margin: 0 auto; margin-bottom: 12px; max-width: 100%; outline: none; text-align: center; text-decoration: none; width: auto;">
                                            </th>
                                            <th class="expander" style="color: #0a0a0a; font-family: 'Roboto', Arial, Helvetica, sans-serif; font-weight: normal; line-height: 1.3; margin: 0; padding: 0; text-align: left;"></th>
                                        </tr>
                                    </table>
                                </th>
                            </tr>
                        </table>
                    </td>
                </tr>
            </table>
        </td>
    </tr>
</table>
</body>
</html>