<?php $this->headScript()
->appendFile($this->basePath('js/typeahead.bundle.min.js'))
->appendFile($this->basePath('js/handlebars.min.js'))?>
<div class="m-subheader">
	<div class="d-flex align-items-center">
 		<div class="mr-auto">
 			<h3 class="m-subheader__title m-subheader__title--separator">Meta tags</h3>
 			<ul class="m-subheader__breadcrumbs m-nav m-nav--inline">
				<li class="m-nav__item m-nav__item--home">
					<a href="<?= $this->url('backend')?>" class="m-nav__link m-nav__link--icon">
					   <i class="m-nav__link-icon la la-home"></i>
					</a>
				</li>
				<li class="m-nav__separator">-</li>
				<li class="m-nav__item">
					<a href="<?= $this->url('backend/trustpilot')?>" class="m-nav__link">
						<span class="m-nav__link-text">Meta tags</span>
					</a>
				</li>
				<li class="m-nav__separator">-</li>
				<li class="m-nav__item">
					<a href="<?= $this->url('backend/trustpilot',['action' => 'add'])?>" class="m-nav__link">
						<span class="m-nav__link-text">New meta tags</span>
					</a>
				</li>
			</ul>
		</div>
	</div>
</div>
<div class="m-content">
	<?php $form->prepare(); echo $this->form()->openTag($form);?>
	<div class="m-portlet m-portlet--success m-portlet--head-solid-bg m-portlet--bordered">
		<?= $this->partial('backend/partial/portlet-head',['title' => 'New meta tags'])?>
		<div class="m-portlet__body">
			<?= $this->showMessages()?>
			<?= $this->formRow($form->get('route'));?>
			<?= $this->formRow($form->get('title'));?>
			<?= $this->formRow($form->get('description'));?>
			<?= $this->formRow($form->get('keywords'));?>
        	<div class="row">
				<div class="col-md-6"><?= $this->formRow($form->get('isEnabled'));?></div>
			</div>
		</div>
		<div class="m-portlet__foot m-portlet__foot--fit">
			<div class="m-form__actions m-form__actions">
				<div class="row">
					<div class="col-lg-12 ml-lg-auto">
						<?= $this->formelement($form->get('submit'));?>
						<?= $this->formelement($form->get('cancel'));?>
					</div>
				</div>
			</div>
		</div>
	</div>
	<?= $this->form()->closeTag()?>
</div>