<div class="m-subheader">
    <div class="d-flex align-items-center">
        <div class="mr-auto">
            <h3 class="m-subheader__title m-subheader__title--separator">Meta Tags</h3>
            <ul class="m-subheader__breadcrumbs m-nav m-nav--inline">
                <li class="m-nav__item m-nav__item--home">
                    <a href="<?= $this->url('backend')?>" class="m-nav__link m-nav__link--icon">
                        <i class="m-nav__link-icon la la-home"></i>
                    </a>
                </li>
                <li class="m-nav__separator">-</li>
                <li class="m-nav__item">
                    <a href="<?= $this->url('backend/trustpilot')?>" class="m-nav__link">
                        <span class="m-nav__link-text">Meta Tags</span>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</div>
<div class="m-content">
    <?= $this->showMessages()?>
    <div class="m-portlet m-portlet--mobile">
        <?= $this->partial('backend/partial/portlet-head',['title' => 'Reviews list'])?>
        <div class="m-portlet__body">
            <div class="m-form m-form--label-align-right m--margin-top-20 m--margin-bottom-30">
                <div class="row align-items-center">
                    <div class="col-xl-6 order-3 order-xl-1">
                        <div class="form-group m-form__group row align-items-center">
                            <div class="col-md-6">
                                <div class="m-input-icon m-input-icon--left">
                                    <input type="text" class="form-control m-input m-input--solid" placeholder="Search..." id="m_form_search">
                                    <span class="m-input-icon__icon m-input-icon__icon--left">
                    					<span><i class="la la-search"></i></span>
                    				</span>
                                </div>
                            </div>
                        </div>
                    </div>
                    <?= $this->partial('backend/partial/tbl-selected')?>
                    <div class="col-xl-2 order-2 order-xl-2 m--align-right">
                        <a href="<?= $this->url('backend/meta_tags',['action' => 'add'])?>" class="btn btn-sm btn-success m-btn m-btn--custom m-btn--icon m-btn--air">
    						<span>
    							<i class="la la-plus"></i>
    							<span>New meta tags</span>
    						</span>
                        </a>
                        <div class="m-separator m-separator--dashed d-xl-none"></div>
                    </div>
                </div>
            </div>

            <table id="table-data" class="m_datatable" width="100%"></table>
        </div>
    </div>
</div>
<?php
$urlGetData = $this->url('backend/meta_tags',['action' => 'get-data']);
$urlEdit = $this->url('backend/meta_tags',['action' => 'edit']);
$urlDelete = $this->url('backend/meta_tags',['action' => 'delete']);
$urlEnable = $this->url('backend/meta_tags',['action' => 'enable']);

$this->inlineScript()->captureStart();
echo <<<JS
    var DatatableRecordSelectionDemo = function() {
        var t = function() {
            var t = $(".m_datatable").mDatatable({
                    data: {
                        type: "remote",
                        source: {
                            read: {
                                url: "$urlGetData"
                            }
                        },
                        pageSize: 20,
                        saveState: {
                            cookie: !0,
                            webstorage: !0
                        },
                        serverPaging: !0,
                        serverFiltering: !0,
                        serverSorting: !0
                    },
                    layout: {
                        theme: "default",
                        class: "",
                        scroll: !0,
                        height: "auto",
                        footer: !1
                    },
                    sortable: !0,
                    toolbar: {
                        placement: ["bottom"],
                        items: {
                            pagination: {
                                pageSizeSelect: [5, 10, 20, 30, 50]
                            }
                        }
                    },
                    columns: [{
                        field: "id",
                        title: "#",
                        sortable: !1,
                        width: 40,
                        textAlign: "center",
                        selector: {
                            class: "m-checkbox--solid m-checkbox--brand"
                        }
                    },{
                        field: "route",
                        title: "Link",
                        textAlign: "left",
                    },{
                        field: "title",
                        title: "Title",
                        textAlign: "left",
                    },{
                        field: "description",
                        title: "Description",
                        textAlign: "left",
                    },{
                        field: "keywords",
                        title: "Keywords",
                        textAlign: "left",
                    },{
                        field: "created",
                        title: "Created Date",
                        textAlign: "left",
                    },{
                        field: "is_enabled",
                        title: "Enabled",
                        width: 100,
                        textAlign: "left",
                        template: function(t){
                            return '<i class="fa '+(t.isEnabled?'fa-check-square-o':'fa-square-o')+'"></i>';
                        }
                    },{
                        field: "Actions",
                        width: 70,
                        title: "Actions",
                        sortable: !1,
                        textAlign: "right",
                        template: function(t) {
                            return '<a href="$urlEdit'+t.id+'" class="m-portlet__nav-link btn m-btn m-btn--hover-accent m-btn--icon m-btn--icon-only m-btn--pill" title="Edit details">\t\t\t\t\t\t\t<i class="la la-edit"></i>\t\t\t\t\t\t</a>'
                            + '\t\t\t\t\t\t<a href="javascript:void(0)" data-id="'+t.id+'" class="delete-btn m-portlet__nav-link btn m-btn m-btn--hover-danger m-btn--icon m-btn--icon-only m-btn--pill" title="Delete">\t\t\t\t\t\t\t<i class="la la-trash"></i>\t\t\t\t\t\t</a>'
                        }
                    }]
                }),
                e = t.getDataSourceQuery();
            $("#m_form_search").on("keyup", function(e) {
                var a = t.getDataSourceQuery();
                a.generalSearch = $(this).val().toLowerCase(), t.setDataSourceQuery(a), t.load()
            }).val(e.generalSearch),
            $("#m_form_region").on("change", function() {
                var e = t.getDataSourceQuery();
                e.region = $(this).val().toLowerCase(), t.setDataSourceQuery(e), t.load()
            }),
            $(".m_datatable").on("m-datatable--on-check", function(e, a) {
                var l = t.setSelectedRecords().getSelectedRecords().length;
                $("#m_datatable_selected_number").html(l), l > 0 && $("#m_datatable_group_action_form").collapse("show")
            }).on("m-datatable--on-uncheck m-datatable--on-layout-updated", function(e, a) {
                var l = t.setSelectedRecords().getSelectedRecords().length;
                $("#m_datatable_selected_number").html(l), 0 === l && $("#m_datatable_group_action_form").collapse("hide")
            }),
            $("#m_datatable_check_all").on('click',function(){
                var idsToDelete = [];
                $.each(t.getSelectedRecords(), function(key, val){
                    idsToDelete.push($(val).find('input[type=checkbox]').val());
                });
                if (confirm('Are you sure?')) {
                    deleteData('$urlDelete',{ids: idsToDelete},t);
                }
            }),
            $("#m_datatable_publish_all").on('click',function(){
                var idsToDelete = [];
                $.each(t.getSelectedRecords(), function(key, val){
                    idsToDelete.push($(val).find('input[type=checkbox]').val());
                });
                if (confirm('Are you sure?')) {
                    deleteData('$urlEnable',{ids: idsToDelete},t);
                }
            }),
            $(".m_datatable").on('click','.delete-btn',function(e){
                e.preventDefault();
                var idsToDelete = [];
                idsToDelete.push($(this).data('id'));
    
                if (confirm('Are you sure?')) {
                    deleteData('$urlDelete',{ids: idsToDelete},t);
                }
            })
        };
        return {
            init: function() {
                t()
            }
        }
    }();

    function deleteData(url, postData, t){
        $.post( url, postData, function( data ) {
            console.log(data);
          if(data.success){
              t.reload();
          }
        }, "json");
    }
    
    jQuery(document).ready(function() {
        DatatableRecordSelectionDemo.init();
    });
JS;
$this->inlineScript()->captureEnd();
?>
