<header class="m-grid__item	m-header "  data-minimize="minimize" data-minimize-offset="200" data-minimize-mobile-offset="200" >
    <div class="m-header__top">
    	<div class="m-container m-container--responsive m-container--xxl m-container--full-height m-page__container">
    		<div class="m-stack m-stack--ver m-stack--desktop">
    			<!-- begin::Brand -->
    			<div class="m-stack__item m-brand">
    				<div class="m-stack m-stack--ver m-stack--general m-stack--inline">
    					<div class="m-stack__item m-stack__item--middle m-brand__logo">
    						<a href="<?= $this->url('backend')?>" class="m-brand__logo-wrapper">
    							<img alt="" src="/backend-theme/img/logo.png"/>
    						</a>
    					</div>
    					<?php if(isset($this->languages) && count($this->languages) > 1):?>
						<div class="m-stack__item m-stack__item--middle m-brand__tools">
							<div class="m-dropdown m-dropdown--inline m-dropdown--arrow m-dropdown--align-left m-dropdown--align-push" data-dropdown-toggle="click">
								<a href="#" class="dropdown-toggle m-dropdown__toggle btn btn-outline-metal m-btn  m-btn--icon m-btn--pill">
                					<span>Language: <?= $this->locale?></span>
                				</a>
                				<div class="m-dropdown__wrapper">
    								<div class="m-dropdown__inner">
                						<div class="m-dropdown__body">
                							<div class="m-dropdown__content">
                								<ul class="m-nav">
                                    				<?php foreach ($this->languages as $lang):?>
                									<li class="m-nav__item">
                										<a href="<?= $this->url('backend/change_language', ['locale' => $lang['locale']])?>?redirectTo=<?= $this->url($this->routeName, $this->routeParams,true)?>" class="m-nav__link">
                											<span class="m-nav__link-text"><?= $lang['name']?></span>
                										</a>
                									</li>
                									<li class="m-nav__separator m-nav__separator--fit"></li>
                                    				<?php endforeach;?>
                								</ul>
                							</div>
                						</div>
                					</div>
            					</div>
							</div>
							<!-- begin::Topbar Toggler-->
							<a id="m_aside_header_topbar_mobile_toggle" href="javascript:;" class="m-brand__icon m--visible-tablet-and-mobile-inline-block">
								<i class="flaticon-more"></i>
							</a>
							<!--end::Topbar Toggler-->
						</div>
                         <?php endif;?>
    				</div>
    			</div>
    			<!-- end::Brand -->
    			<!-- begin::Topbar -->
    			<div class="m-stack__item m-stack__item--fluid m-header-head" id="m_header_nav">
    				<div id="m_header_topbar" class="m-topbar  m-stack m-stack--ver m-stack--general">
    					<div class="m-stack__item m-topbar__nav-wrapper">
    						<ul class="m-topbar__nav m-nav m-nav--inline">
    							<li class="m-nav__item m-topbar__user-profile m-topbar__user-profile--img  m-dropdown m-dropdown--medium m-dropdown--arrow m-dropdown--header-bg-fill m-dropdown--align-right m-dropdown--mobile-full-width m-dropdown--skin-light" data-dropdown-toggle="click">
    								<a href="#" class="m-nav__link m-dropdown__toggle">
    									<span class="m-topbar__welcome">
    										Hello,&nbsp;
    									</span>
    									<span class="m-topbar__username">
    										<?= $this->identity()->getNickname()?>
    									</span>
    									<span class="m-topbar__userpic"></span>
    								</a>
    								<div class="m-dropdown__wrapper">
    									<span class="m-dropdown__arrow m-dropdown__arrow--right m-dropdown__arrow--adjust"></span>
    									<div class="m-dropdown__inner">
    										<div class="m-dropdown__header m--align-center" style="background: url(/backend-theme/assets/app/media/img/misc/user_profile_bg.jpg); background-size: cover;">
    											<div class="m-card-user m-card-user--skin-dark">
    												<div class="m-card-user__pic"></div>
    												<div class="m-card-user__details">
    													<span class="m-card-user__name m--font-weight-500">
    														<?= $this->identity()->getNickname()?>
    													</span>
    													<a href="<?= $this->url('backend/profile')?>" class="m-card-user__email m--font-weight-300 m-link">
    														<?= $this->identity()->getEmail()?>
    													</a>
    												</div>
    											</div>
    										</div>
    										<div class="m-dropdown__body">
    											<div class="m-dropdown__content">
    												<ul class="m-nav m-nav--skin-light">
    													<li class="m-nav__item">
    														<a href="<?= $this->url('backend/default',['action' => 'logout'])?>" class="btn m-btn--pill btn-secondary m-btn m-btn--custom m-btn--label-brand m-btn--bolder">
    															Logout
    														</a>
    													</li>
    												</ul>
    											</div>
    										</div>
    									</div>
    								</div>
    							</li>
    						</ul>
    					</div>
    				</div>
    			</div>
    			<!-- end::Topbar -->
    		</div>
    	</div>
    </div>
    <div class="m-header__bottom">
    	<div class="m-container m-container--responsive m-container--xxl m-container--full-height m-page__container">
    		<div class="m-stack m-stack--ver m-stack--desktop">
    			<!-- begin::Horizontal Menu -->
    			<div class="m-stack__item m-stack__item--middle m-stack__item--fluid">
    				<button class="m-aside-header-menu-mobile-close  m-aside-header-menu-mobile-close--skin-light " id="m_aside_header_menu_mobile_close_btn">
    					<i class="la la-close"></i>
    				</button>
    				<div id="m_header_menu" class="m-header-menu m-aside-header-menu-mobile m-aside-header-menu-mobile--offcanvas  m-header-menu--skin-dark m-header-menu--submenu-skin-light m-aside-header-menu-mobile--skin-light m-aside-header-menu-mobile--submenu-skin-light "  >
    					<?php $access = $_SESSION['Zend_Auth']->__get("session")->getAccess(); ?>
                        <?= $this->navigation("Zend\Navigation\\$access")->menu()->setMinDepth(1)->setPartial('backend/partial/menu') ?>
    				</div>
    			</div>
    			<!-- end::Horizontal Menu -->
    			</div>
    		</div>
    	</div>
    </header>