<div class="col-xl-4 order-3 order-xl-1">	
	<div class="form-group m-form__group row align-items-center">
		<div class="col-md-10">
			<div class="m-input-icon m-input-icon--left">
				<input type="text" class="form-control m-input m-input--solid" placeholder="Search..." id="m_form_search">
				<span class="m-input-icon__icon m-input-icon__icon--left">
					<span><i class="la la-search"></i></span>
				</span>
			</div>
		</div>
	</div>
</div>