<div class="col-xl-4 order-1 order-xl-2 m--align-right">
	<div class="row align-items-center collapse"  id="m_datatable_group_action_form">
		<div class="col-xl-12">
			<div class="m-form__group m-form__group--inline">
				<div class="m-form__label m-form__label-no-wrap">
					<label class="m--font-bold m--font-danger-">Selected <span id="m_datatable_selected_number">0</span> records:</label>
				</div>
				<div class="m-form__control">
					<div class="btn-toolbar">
						<button class="btn btn-sm btn-danger" type="button" id="m_datatable_check_all">Delete All</button>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>