<div class="m-subheader">
	<div class="d-flex align-items-center">
 		<div class="mr-auto">
 			<h3 class="m-subheader__title m-subheader__title--separator">Settings</h3>
 			<ul class="m-subheader__breadcrumbs m-nav m-nav--inline">
				<li class="m-nav__item m-nav__item--home">
					<a href="<?= $this->url('backend')?>" class="m-nav__link m-nav__link--icon">
					   <i class="m-nav__link-icon la la-home"></i>
					</a>
				</li>
				<li class="m-nav__separator">-</li>
				<li class="m-nav__item">
					<a href="<?= $this->url('backend/setting')?>" class="m-nav__link">
						<span class="m-nav__link-text">Settings</span>
					</a>
				</li>
			</ul>
		</div>
	</div>
</div>
<div class="m-content">
	<?= $this->showMessages()?>
	<div class="m-portlet m-portlet--mobile">
		<?= $this->partial('backend/partial/portlet-head',['title' => 'Setting list'])?>
		<div class="m-portlet__body">
			<div class="m-form m-form--label-align-right m--margin-top-20 m--margin-bottom-30">
				<div class="row align-items-center">
    				<?= $this->partial('backend/partial/tbl-search')?>
    				<?= $this->partial('backend/partial/tbl-selected')?>
    				<div class="col-xl-4 order-2 order-xl-2 m--align-right">
    					<a href="<?= $this->url('backend/setting',['action' => 'add'])?>" class="btn btn-sm btn-success m-btn m-btn--custom m-btn--icon m-btn--air">
    						<span>
    							<i class="la la-plus"></i>
    							<span>New Setting</span>
    						</span>
    					</a>
    					<div class="m-separator m-separator--dashed d-xl-none"></div>
    				</div>
    			</div>
			</div>

			<table id="table-data" class="m_datatable" width="100%"></table>
		</div>
	</div>
</div>
<?php
$urlGetData = $this->url('backend/setting',['action' => 'get-data']);
$urlDelete = $this->url('backend/setting',['action' => 'delete']);
$urlEdit = $this->url('backend/setting',['action' => 'edit']);
$this->inlineScript()->captureStart();
echo <<<JS
var DatatableRecordSelectionDemo = function() {
    var t = function() {
        var t = $(".m_datatable").mDatatable({
	            data: {
	                type: "remote",
	                source: {
	                    read: {
	                        url: "$urlGetData"
	                    }
	                },
	                pageSize: 20,
	                saveState: {
	                    cookie: !0,
	                    webstorage: !0
	                },
	                serverPaging: !0,
	                serverFiltering: !0,
	                serverSorting: !0
	            },
	            layout: {
	                theme: "default",
	                class: "",
	                scroll: !0,
	                height: "auto",
	                footer: !1
	            },
	            sortable: !0,
	            toolbar: {
	                placement: ["bottom"],
	                items: {
	                    pagination: {
	                        pageSizeSelect: [5, 10, 20, 30, 50]
	                    }
	                }
	            },
                columns: [{
                    field: "id",
                    title: "#",
                    sortable: !1,
                    width: 40,
                    textAlign: "center",
                    selector: {
                        class: "m-checkbox--solid m-checkbox--brand"
                    }
                },{
                    field: "code",
                    title: "Code",
                    width: 180,
                    textAlign: "left",
                },{
                    field: "value",
                    title: "Value",
                    width: 700,
                    textAlign: "left",
                },{
                    field: "Actions",
                    width: 70,
                    title: "Actions",
                    sortable: !1,
                    textAlign: "right",
                    template: function(t) {
                        return '<a href="$urlEdit'+t.id+'" class="m-portlet__nav-link btn m-btn m-btn--hover-accent m-btn--icon m-btn--icon-only m-btn--pill" title="Edit details">\t\t\t\t\t\t\t<i class="la la-edit"></i>\t\t\t\t\t\t</a>'
                        + '\t\t\t\t\t\t<a href="javascript:void(0)" data-id="'+t.id+'" class="delete-btn m-portlet__nav-link btn m-btn m-btn--hover-danger m-btn--icon m-btn--icon-only m-btn--pill" title="Delete">\t\t\t\t\t\t\t<i class="la la-trash"></i>\t\t\t\t\t\t</a>'
                    }
                }]
            }),
            e = t.getDataSourceQuery();
        $("#m_form_search").on("keyup", function(e) {
            var a = t.getDataSourceQuery();
            a.generalSearch = $(this).val().toLowerCase(), t.setDataSourceQuery(a), t.load()
        }).val(e.generalSearch),
        $(".m_datatable").on("m-datatable--on-check", function(e, a) {
            var l = t.setSelectedRecords().getSelectedRecords().length;
            $("#m_datatable_selected_number").html(l), l > 0 && $("#m_datatable_group_action_form").collapse("show")
        }).on("m-datatable--on-uncheck m-datatable--on-layout-updated", function(e, a) {
            var l = t.setSelectedRecords().getSelectedRecords().length;
            $("#m_datatable_selected_number").html(l), 0 === l && $("#m_datatable_group_action_form").collapse("hide")
        }),
        $("#m_datatable_check_all").on('click',function(){
        	var idsToDelete = [];
        	$.each(t.getSelectedRecords(), function(key, val){
        		idsToDelete.push($(val).find('input[type=checkbox]').val());
        	});
        	if (confirm('Are you sure?')) {
        		deleteData('$urlDelete',{ids: idsToDelete},t);
    		}
        }),
        $(".m_datatable").on('click','.delete-btn',function(e){
        	e.preventDefault();
        	var idsToDelete = [];
        	idsToDelete.push($(this).data('id'));

        	if (confirm('Are you sure?')) {
        		deleteData('$urlDelete',{ids: idsToDelete},t);
    		}
        })
    };
    return {
        init: function() {
            t()
        }
    }
}();

function deleteData(url, postData, t){
	$.post( url, postData, function( data ) {
	  if(data.success){
		  t.reload();
	  }
	}, "json");
}

jQuery(document).ready(function() {
    DatatableRecordSelectionDemo.init()
});
JS;
$this->inlineScript()->captureEnd();
?>