<div class="m-subheader">
	<div class="d-flex align-items-center">
 		<div class="mr-auto">
 			<h3 class="m-subheader__title m-subheader__title--separator">Socials</h3>
 			<ul class="m-subheader__breadcrumbs m-nav m-nav--inline">
				<li class="m-nav__item m-nav__item--home">
					<a href="<?= $this->url('backend')?>" class="m-nav__link m-nav__link--icon">
					   <i class="m-nav__link-icon la la-home"></i>
					</a>
				</li>
				<li class="m-nav__separator">-</li>
				<li class="m-nav__item">
					<a href="<?= $this->url('backend/social')?>" class="m-nav__link">
						<span class="m-nav__link-text">Socials</span>
					</a>
				</li>
				<li class="m-nav__separator">-</li>
				<li class="m-nav__item">
					<a href="<?= $this->url('backend/social',['action' => 'add'])?>" class="m-nav__link">
						<span class="m-nav__link-text">New link</span>
					</a>
				</li>
			</ul>
		</div>
	</div>
</div>
<div class="m-content">
	<div class="row">
	<div class="col-lg-6">
	<?php $form->prepare(); echo $this->form()->openTag($form);?>
	<div class="m-portlet m-portlet--success m-portlet--head-solid-bg m-portlet--bordered">
		<?= $this->partial('backend/partial/portlet-head',['title' => 'New type'])?>
		<div class="m-portlet__body">
			<?= $this->showMessages()?>
			<?= $this->formRow($form->get('type'));?>
			<?= $this->formRow($form->get('link'));?>
			<?= $this->formRow($form->get('sort'));?>
		</div>
		<div class="m-portlet__foot m-portlet__foot--fit">
			<div class="m-form__actions m-form__actions">
				<div class="row">
					<div class="col-lg-12 ml-lg-auto">
						<?= $this->formelement($form->get('submit'));?>
						<?= $this->formelement($form->get('cancel'));?>
					</div>
				</div>
			</div>
		</div>
	</div>
	<?= $this->form()->closeTag()?>
	</div>
	</div>
</div>
<?php
$this->inlineScript()->captureStart();
echo <<<JS
JS;
$this->inlineScript()->captureEnd();
?>