<div class="m-login__signin">
	<div class="m-login__head">
		<h3 class="m-login__title">Forgotten Password ?</h3>
		<div class="m-login__desc">Enter your email to reset your password:</div>
	</div>
	<?php $form->prepare(); echo $this->form()->openTag($form);?>
		<?= $this->showMessages()?>
		<div class="form-group m-form__group">
			<?= $this->formRow($form->get('email'));?>
		</div>
		<div class="m-login__form-action">
			<button id="m_login_forget_password_submit" name="submit" class="btn btn-focus m-btn m-btn--pill m-btn--custom m-btn--air  m-login__btn m-login__btn--primaryr">Request</button>&nbsp;&nbsp;
			<button id="m_login_forget_password_cancel" name="cancel" class="btn btn-outline-focus m-btn m-btn--pill m-btn--custom m-login__btn">Cancel</button>
		</div>
	<?= $this->form()->closeTag();?> 
</div>